In [1]:
import json
import numpy as np
import pandas as pd

In [2]:
# Abrir o arquivo de tweets e ler as linhas
with open('collected_tweets2020-49-01-20-49-31.txt','r') as file:
    tweets = file.readlines()

In [3]:
# Fazendo parsens e escrevendo novo arquivo JSON
# with open('tweet.json','w') as f:
#     json.dump(
#         json.loads(json.loads(tweets[0])),f
#     )

In [3]:
# Tipo dos nossos dados
type(
    json.loads(
        json.loads(tweets[0])
    )    
)

dict

# Acessando as chaves JSON (Dicionário)

In [4]:
parsed_tweets = [json.loads(json.loads(i)) for i in tweets]

In [5]:
# parsed_tweets[1]

In [6]:
# Numero de linhas 
len(parsed_tweets)

53466

In [8]:
primeiro_tweet = parsed_tweets[0]

In [9]:
list(primeiro_tweet.items())[1]

('id', 1333921183415189505)

In [10]:
primeiro_tweet.keys()

dict_keys(['created_at', 'id', 'id_str', 'text', 'display_text_range', 'source', 'truncated', 'in_reply_to_status_id', 'in_reply_to_status_id_str', 'in_reply_to_user_id', 'in_reply_to_user_id_str', 'in_reply_to_screen_name', 'user', 'geo', 'coordinates', 'place', 'contributors', 'is_quote_status', 'extended_tweet', 'quote_count', 'reply_count', 'retweet_count', 'favorite_count', 'entities', 'favorited', 'retweeted', 'filter_level', 'lang', 'timestamp_ms'])

In [11]:
# acessando texto do tweet, chave de primeiro nivel (root)
primeiro_tweet['text']

'@DailyCaller @MariaBartiromo Aren’t most journalists knowledgeable in laws and reality of another’s interpretation… https://t.co/GKlfCTWvzf'

In [12]:
primeiro_tweet['user']

{'id': 1050224102126964737,
 'id_str': '1050224102126964737',
 'name': 'WeAreAllGoodPeople,Not',
 'screen_name': 'cmebmebhappy',
 'location': 'Possibly somewhere up high ',
 'url': None,
 'description': 'Just like to hear many different views. It is great to interact.I have lots of opinions. Liberal. Unity. #Biden2020 #ByeDon #MoscowMitch',
 'translator_type': 'none',
 'protected': False,
 'verified': False,
 'followers_count': 509,
 'friends_count': 501,
 'listed_count': 0,
 'favourites_count': 2424,
 'statuses_count': 2962,
 'created_at': 'Thu Oct 11 03:18:32 +0000 2018',
 'utc_offset': None,
 'time_zone': None,
 'geo_enabled': False,
 'lang': None,
 'contributors_enabled': False,
 'is_translator': False,
 'profile_background_color': 'F5F8FA',
 'profile_background_image_url': '',
 'profile_background_image_url_https': '',
 'profile_background_tile': False,
 'profile_link_color': '1DA1F2',
 'profile_sidebar_border_color': 'C0DEED',
 'profile_sidebar_fill_color': 'DDEEF6',
 'profile_text_color': '333333',
 'profile_use_background_image': True,
 'profile_image_url': 'http://pbs.twimg.com/profile_images/1322451395820232704/O1tn01Gm_normal.jpg',
 'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1322451395820232704/O1tn01Gm_normal.jpg',
 'profile_banner_url': 'https://pbs.twimg.com/profile_banners/1050224102126964737/1591981569',
 'default_profile': True,
 'default_profile_image': False,
 'following': None,
 'follow_request_sent': None,
 'notifications': None}

In [13]:
primeiro_tweet['user']['screen_name']

'cmebmebhappy'

# Transformar os tweets em uma estrutura relacional analisável

In [14]:
df_tratado = pd.DataFrame(parsed_tweets[1]).reset_index(drop=True).iloc[:1]
df_tratado

,created_at,id,id_str,text,source,truncated,in_reply_to_status_id,in_reply_to_status_id_str,in_reply_to_user_id,in_reply_to_user_id_str,...,quote_count,reply_count,retweet_count,favorite_count,entities,favorited,retweeted,filter_level,lang,timestamp_ms
0,Tue Dec 01 23:49:27 +0000 2020,1333921183503355904,1333921183503355904,RT @chiIIum: Don’t you dare give up on Preside...,"<a href=""http://twitter.com/download/iphone"" r...",False,None,None,None,None,...,0,0,0,0,NaN,False,False,low,en,1606866567861

In [15]:
df_tratado.columns

Index(['created_at', 'id', 'id_str', 'text', 'source', 'truncated',
       'in_reply_to_status_id', 'in_reply_to_status_id_str',
       'in_reply_to_user_id', 'in_reply_to_user_id_str',
       'in_reply_to_screen_name', 'user', 'geo', 'coordinates', 'place',
       'contributors', 'retweeted_status', 'is_quote_status', 'quote_count',
       'reply_count', 'retweet_count', 'favorite_count', 'entities',
       'favorited', 'retweeted', 'filter_level', 'lang', 'timestamp_ms'],
      dtype='object')

In [16]:
df_tratado.drop(columns=['quote_count','reply_count', 'retweet_count', 
                         'favorite_count','favorited', 'retweeted',
                        'user', 'retweeted_status','entities'], inplace=True)

In [17]:
df_tratado.columns

Index(['created_at', 'id', 'id_str', 'text', 'source', 'truncated',
       'in_reply_to_status_id', 'in_reply_to_status_id_str',
       'in_reply_to_user_id', 'in_reply_to_user_id_str',
       'in_reply_to_screen_name', 'geo', 'coordinates', 'place',
       'contributors', 'is_quote_status', 'filter_level', 'lang',
       'timestamp_ms'],
      dtype='object')

In [18]:
df_tratado['user_id'] = parsed_tweets[1]['user']['id']
df_tratado['user_id_str'] = parsed_tweets[1]['user']['id_str']
df_tratado['user_screen_name'] = parsed_tweets[1]['user']['screen_name']
df_tratado['user_location'] = parsed_tweets[1]['user']['location']
df_tratado['user_description'] = parsed_tweets[1]['user']['description']
df_tratado['user_protected'] = parsed_tweets[1]['user']['protected']
df_tratado['user_verified'] = parsed_tweets[1]['user']['verified']
df_tratado['user_followers_count'] = parsed_tweets[1]['user']['followers_count']
df_tratado['user_friends_count'] = parsed_tweets[1]['user']['friends_count']
df_tratado['user_created_at'] = parsed_tweets[1]['user']['created_at']

In [19]:
df_tratado

,created_at,id,id_str,text,source,truncated,in_reply_to_status_id,in_reply_to_status_id_str,in_reply_to_user_id,in_reply_to_user_id_str,...,user_id,user_id_str,user_screen_name,user_location,user_description,user_protected,user_verified,user_followers_count,user_friends_count,user_created_at
0,Tue Dec 01 23:49:27 +0000 2020,1333921183503355904,1333921183503355904,RT @chiIIum: Don’t you dare give up on Preside...,"<a href=""http://twitter.com/download/iphone"" r...",False,None,None,None,None,...,875922981733548032,875922981733548032,HollySh43407891,None,"American Patriot, Conservative, Christian, TRU...",False,False,381,1065,Sat Jun 17 03:48:07 +0000 2017

In [20]:
# Entidades
parsed_tweets[1]['entities']

{'hashtags': [],
 'urls': [],
 'user_mentions': [{'screen_name': 'chiIIum',
   'name': '𝕔hi𝓁𝓁iຖ໐iˢ',
   'id': 466183294,
   'id_str': '466183294',
   'indices': [3, 11]}],
 'symbols': []}

In [21]:
user_mentions = []

for i in range(len(parsed_tweets[1]['entities']['user_mentions'])):
    dict_base = parsed_tweets[1]['entities']['user_mentions'][i].copy()
    dict_base.pop('indices', None)
    df = pd.DataFrame(dict_base, index=[0])
    df = df.rename(columns={
        'screen_name': 'entites_screen_name',
        'name': 'entites_id',
        'id_str': 'entites_id_str'
    })
    user_mentions.append(df)

In [22]:
user_mentions

[  entites_screen_name  entites_id         id entites_id_str
 0             chiIIum  𝕔hi𝓁𝓁iຖ໐iˢ  466183294      466183294]

In [23]:
dfs = []

for i in user_mentions:
    dfs.append(
        pd.concat([df_tratado.copy(), i], axis=1)
    )

In [24]:
dfs

[                       created_at                   id               id_str  \
 0  Tue Dec 01 23:49:27 +0000 2020  1333921183503355904  1333921183503355904

                                                 text  \
 0  RT @chiIIum: Don’t you dare give up on Preside...

                                               source  truncated  \
 0  <a href="http://twitter.com/download/iphone" r...      False

   in_reply_to_status_id in_reply_to_status_id_str in_reply_to_user_id  \
 0                  None                      None                None

   in_reply_to_user_id_str  ...  \
 0                    None  ...

                                     user_description user_protected  \
 0  American Patriot, Conservative, Christian, TRU...          False

   user_verified user_followers_count user_friends_count  \
 0         False                  381               1065

                   user_created_at entites_screen_name  entites_id         id  \
 0  Sat Jun 17 03:48:07 +0000 2017             chiIIum  𝕔hi𝓁𝓁iຖ໐iˢ  466183294

    entites_id_str
 0       466183294

 [1 rows x 33 columns]]

In [25]:
pd.concat(dfs, ignore_index=True)

,created_at,id,id_str,text,source,truncated,in_reply_to_status_id,in_reply_to_status_id_str,in_reply_to_user_id,in_reply_to_user_id_str,...,user_description,user_protected,user_verified,user_followers_count,user_friends_count,user_created_at,entites_screen_name,entites_id,id,entites_id_str
0,Tue Dec 01 23:49:27 +0000 2020,1333921183503355904,1333921183503355904,RT @chiIIum: Don’t you dare give up on Preside...,"<a href=""http://twitter.com/download/iphone"" r...",False,None,None,None,None,...,"American Patriot, Conservative, Christian, TRU...",False,False,381,1065,Sat Jun 17 03:48:07 +0000 2017,chiIIum,𝕔hi𝓁𝓁iຖ໐iˢ,466183294,466183294

   # Vamos criar uma função que converter tweets para um DataFrame

In [26]:
def tweets_para_df(tweet):
    try:
        df_tratado = pd.DataFrame(tweet).reset_index(drop=True).iloc[:1]

        df_tratado.drop(columns=['quote_count','reply_count', 'retweet_count', 
                                 'favorite_count','favorited', 'retweeted', 'user',
                                 'retweeted_status','entities'], inplace=True)

        df_tratado['user_id'] = tweet['user']['id']
        df_tratado['user_id_str'] = tweet['user']['id_str']
        df_tratado['user_screen_name'] = tweet['user']['screen_name']
        df_tratado['user_location'] = tweet['user']['location']
        df_tratado['user_description'] = tweet['user']['description']
        df_tratado['user_protected'] = tweet['user']['protected']
        df_tratado['user_verified'] = tweet['user']['verified']
        df_tratado['user_followers_count'] = tweet['user']['followers_count']
        df_tratado['user_friends_count'] = tweet['user']['friends_count']
        df_tratado['user_created_at'] = tweet['user']['created_at']

        user_mentions = []

        for i in range(len(tweet['entities']['user_mentions'])):
            dict_base = tweet['entities']['user_mentions'][i].copy()
            dict_base.pop('indices', None)
            df = pd.DataFrame(dict_base, index=[0])
            df = df.rename(columns={
                'screen_name': 'entites_screen_name',
                'name': 'entites_id',
                'id_str': 'entites_id_str'
            })
            user_mentions.append(df)

        dfs = []

        for i in user_mentions:
            dfs.append(pd.concat([df_tratado.copy(), i], axis=1))
            
        df_final = pd.concat(dfs, ignore_index=True)
    
    except:    
        return None
    
    return df_final

In [27]:
tweets_para_df(parsed_tweets[6])

,created_at,id,id_str,text,source,truncated,in_reply_to_status_id,in_reply_to_status_id_str,in_reply_to_user_id,in_reply_to_user_id_str,...,user_description,user_protected,user_verified,user_followers_count,user_friends_count,user_created_at,entites_screen_name,entites_id,id,entites_id_str
0,Tue Dec 01 23:49:27 +0000 2020,1333921183885127680,1333921183885127680,RT @maggieNYT: .@abc confirms our story on Giu...,"<a href=""http://twitter.com/download/iphone"" r...",False,None,None,None,None,...,"Biologist, NO DMs, views/opinions my own, RT/F...",False,False,1535,1089,Sat Aug 22 17:12:46 +0000 2009,maggieNYT,Maggie Haberman,93069110,93069110
1,Tue Dec 01 23:49:27 +0000 2020,1333921183885127680,1333921183885127680,RT @maggieNYT: .@abc confirms our story on Giu...,"<a href=""http://twitter.com/download/iphone"" r...",False,None,None,None,None,...,"Biologist, NO DMs, views/opinions my own, RT/F...",False,False,1535,1089,Sat Aug 22 17:12:46 +0000 2009,ABC,ABC News,28785486,28785486

In [28]:
%%time
# Vamos iterar e transformar todos os tweets
parseados = [tweets_para_df(tweet) for tweet in parsed_tweets]

CPU times: user 15min 3s, sys: 1.33 s, total: 15min 4s
Wall time: 15min 3s

In [29]:
#Eliminar as posições vazias da lista 
parseados = [i for i in parseados if i is not None]

In [30]:
parseados[10]

,created_at,id,id_str,text,source,truncated,in_reply_to_status_id,in_reply_to_status_id_str,in_reply_to_user_id,in_reply_to_user_id_str,...,user_description,user_protected,user_verified,user_followers_count,user_friends_count,user_created_at,entites_screen_name,entites_id,id,entites_id_str
0,Tue Dec 01 23:49:28 +0000 2020,1333921184442851328,1333921184442851328,"RT @news_ntd: ""I find it highly implausible be...","<a href=""https://mobile.twitter.com"" rel=""nofo...",False,None,None,None,None,...,"Love reading, dogs, baking, sleep, and helping",False,False,35,71,Tue Oct 29 22:37:32 +0000 2019,news_ntd,NTD News,1060573081935249409,1060573081935249409

In [31]:
tratado = pd.concat(parseados[:10], ignore_index=True)

In [32]:
tratado

,created_at,id,id_str,text,source,truncated,in_reply_to_status_id,in_reply_to_status_id_str,in_reply_to_user_id,in_reply_to_user_id_str,...,user_description,user_protected,user_verified,user_followers_count,user_friends_count,user_created_at,entites_screen_name,entites_id,id,entites_id_str
0,Tue Dec 01 23:49:27 +0000 2020,1333921183503355904,1333921183503355904,RT @chiIIum: Don’t you dare give up on Preside...,"<a href=""http://twitter.com/download/iphone"" r...",False,None,None,None,None,...,"American Patriot, Conservative, Christian, TRU...",False,False,381,1065,Sat Jun 17 03:48:07 +0000 2017,chiIIum,𝕔hi𝓁𝓁iຖ໐iˢ,466183294,466183294
1,Tue Dec 01 23:49:27 +0000 2020,1333921183763476482,1333921183763476482,RT @robreiner: Donald Trump is a Loser. His wh...,"<a href=""http://twitter.com/download/iphone"" r...",False,None,None,None,None,...,None,False,False,20,53,Thu Jun 04 17:09:38 +0000 2020,robreiner,Rob Reiner,738080573365702657,738080573365702657
2,Tue Dec 01 23:49:27 +0000 2020,1333921183792730112,1333921183792730112,RT @MrMichaelBurkes: Raise your hand if Trump ...,"<a href=""http://twitter.com/download/android"" ...",False,None,None,None,None,...,Pro- God Family Country Israel Guns and Pro Li...,False,False,915,1802,Tue Aug 25 06:10:06 +0000 2020,MrMichaelBurkes,Trump's Black Grandson,199841160,199841160
3,Tue Dec 01 23:49:27 +0000 2020,1333921183880912896,1333921183880912896,RT @CindyKendrick11: Trump never had a chance ...,"<a href=""http://twitter.com/download/iphone"" r...",False,None,None,None,None,...,STOP THE http://STEAL.US,False,False,300,438,Sun Oct 18 10:33:35 +0000 2020,CindyKendrick11,Sassy ass Cindy,1144128948240035840,1144128948240035840
4,Tue Dec 01 23:49:27 +0000 2020,1333921183885127680,1333921183885127680,RT @maggieNYT: .@abc confirms our story on Giu...,"<a href=""http://twitter.com/download/iphone"" r...",False,None,None,None,None,...,"Biologist, NO DMs, views/opinions my own, RT/F...",False,False,1535,1089,Sat Aug 22 17:12:46 +0000 2009,maggieNYT,Maggie Haberman,93069110,93069110
5,Tue Dec 01 23:49:27 +0000 2020,1333921183885127680,1333921183885127680,RT @maggieNYT: .@abc confirms our story on Giu...,"<a href=""http://twitter.com/download/iphone"" r...",False,None,None,None,None,...,"Biologist, NO DMs, views/opinions my own, RT/F...",False,False,1535,1089,Sat Aug 22 17:12:46 +0000 2009,ABC,ABC News,28785486,28785486
6,Tue Dec 01 23:49:27 +0000 2020,1333921183968976896,1333921183968976896,RT @glendimar2512: Díaz-Canel denuncia último ...,"<a href=""http://twitter.com/download/android"" ...",False,None,None,None,None,...,Intento cada día dar lo mejor de mí siendo #Tu...,False,False,1751,1749,Mon Aug 10 15:48:39 +0000 2020,glendimar2512,glendimar2512,1250115796740825102,1250115796740825102
7,Tue Dec 01 23:49:28 +0000 2020,1333921184157667333,1333921184157667333,RT @kylenabecker: Do you remember all those pu...,"<a href=""http://twitter.com/download/iphone"" r...",False,None,None,None,None,...,None,False,False,57,301,Sat Oct 20 01:18:35 +0000 2012,kylenabecker,Kyle Becker,321954654,321954654
8,Tue Dec 01 23:49:28 +0000 2020,1333921184325492742,1333921184325492742,RT @heather_giron: To those who keep saying Pr...,"<a href=""https://mobile.twitter.com"" rel=""nofo...",False,None,None,None,None,...,made for another world - Psalm 27:3 ⚔️,False,False,1095,2136,Sat Dec 14 18:58:17 +0000 2019,heather_giron,Heather Giron 𝓜𝓐𝓖𝓐 𝓒𝓸𝓾𝓷𝓽𝓻𝔂🇺🇸,1216745530711212037,1216745530711212037
9,Tue Dec 01 23:49:28 +0000 2020,1333921184447041537,1333921184447041537,"RT @Rschooley: Just to be clear, Trump's lawye...","<a href=""http://twitter.com/download/iphone"" r...",False,None,None,None,None,...,Go Phillies and go Dinos. That’s one of my she...,False,False,81,669,Sat Jul 14 03:23:32 +0000 2018,Rschooley,Schooley,66213051,66213051
10,Tue Dec 01 23:49:28 +0000 2020,1333921184350695429,1333921184350695429,RT @WayneDupreeShow: Lieutenant General Thomas...,"<a href=""http://twitter.com/download/iphone"" r...",False,None,None,None,None,...,None,False,False,7,205,Thu Jun 27 00:23:56 +0000 2019,WayneDupreeShow,"Wayne Dupree Media, LLC",282695161,282695161

# Ingestão de dados do Twitter no POSTGRESQL

In [40]:
import io
from sqlalchemy import create_engine
import psycopg2

In [41]:
engine = create_engine('postgresql://postgres:1234@127.0.0.1/twitter')

In [42]:
tratado.to_sql("tweet", con=engine, index=False, if_exists="append")